### ISSUE TITLE
java.lang.AbstractMethodError: org.killbill.billing.plugin.simpletax.SimpleTaxPlugin.getAdditionalInvoiceItems

### ISSUE THREAD

**Issue by adamlc** [bgandon/killbill-simple-tax-plugin#2]
Hey,

Would just like to say thanks for writing this plugin, I realise it still may be a work in progress, but Im getting this error when creating a Subscription:

```
2016-01-13 09:21:04,376 [bus_events-th] ERROR o.k.c.concurrent.LoggingExecutor - Thread[bus_events-th,5,bus-grp] ended with an exception
java.lang.AbstractMethodError: org.killbill.billing.plugin.simpletax.SimpleTaxPlugin.getAdditionalInvoiceItems(Lorg/killbill/billing/invoice/api/Invoice;ZLjava/lang/Iterable;Lorg/killbill/billing/util/callcontext/CallContext;)Ljava/util/List;
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.killbill.billing.osgi.ContextClassLoaderHelper$ClassLoaderInvocationHandler$1.execute(ContextClassLoaderHelper.java:142)
    at org.killbill.commons.profiling.Profiling.executeWithProfiling(Profiling.java:33)
    at org.killbill.billing.osgi.ContextClassLoaderHelper$ClassLoaderInvocationHandler.invoke(ContextClassLoaderHelper.java:139)
    at com.sun.proxy.$Proxy121.getAdditionalInvoiceItems(Unknown Source)
    at org.killbill.billing.invoice.InvoicePluginDispatcher.getAdditionalInvoiceItems(InvoicePluginDispatcher.java:67)
    at org.killbill.billing.invoice.InvoiceDispatcher.processAccountWithLockAndInputTargetDate(InvoiceDispatcher.java:349)
    at org.killbill.billing.invoice.InvoiceDispatcher.processAccountWithLock(InvoiceDispatcher.java:244)
    at org.killbill.billing.invoice.InvoiceDispatcher.processAccount(InvoiceDispatcher.java:213)
    at org.killbill.billing.invoice.InvoiceDispatcher.processSubscriptionInternal(InvoiceDispatcher.java:199)
    at org.killbill.billing.invoice.InvoiceDispatcher.processSubscriptionForInvoiceGeneration(InvoiceDispatcher.java:174)
    at org.killbill.billing.invoice.InvoiceDispatcher.processSubscriptionForInvoiceGeneration(InvoiceDispatcher.java:170)
    at org.killbill.billing.invoice.InvoiceListener.handleSubscriptionTransition(InvoiceListener.java:89)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.EventBusThatThrowsException.dispatchWithException(EventBusThatThrowsException.java:106)
    at com.google.common.eventbus.EventBusThatThrowsException.dispatchQueuedEventsWithException(EventBusThatThrowsException.java:94)
    at com.google.common.eventbus.EventBusThatThrowsException.postWithException(EventBusThatThrowsException.java:82)
    at org.killbill.bus.DefaultPersistentBus.dispatchBusEventWithMetrics(DefaultPersistentBus.java:299)
    at org.killbill.bus.dispatching.BusCallableCallback.dispatch(BusCallableCallback.java:40)
    at org.killbill.bus.dispatching.BusCallableCallback.dispatch(BusCallableCallback.java:29)
    at org.killbill.queue.dispatching.Dispatcher$CallableQueue.call(Dispatcher.java:102)
    at org.killbill.queue.dispatching.Dispatcher$CallableQueue.call(Dispatcher.java:85)
    at org.killbill.commons.concurrent.WrappedCallable.call(WrappedCallable.java:42)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at org.killbill.commons.concurrent.WrappedRunnable.run(WrappedRunnable.java:40)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
```

The invoice never gets created. I have the tax country set on the account. I have tried with and without the vat_in. Am I doing something wrong or missing something? I'm using KB 0.16 :)

Thanks!

**Comment by bgandon** [comment]
Sorry for the delay of my answer. I didn't see the notification until now.

This must be related to the invoice plugin API having added one more parameter in the `getAdditionalInvoiceItems()` method in version 0.15.3 or 0.15.4. This method is the main entry point of the simple-tax plugin.

I'm still developing the plugin with Kill Bill 0.15.2, which uses the same API as 0.14.

So in short, the simple-tax plugin is not updated yet to be used in a 0.16 environment. Sorry for that.
